In [1]:
import pandas as pd
import numpy as np
import os
import healpy as hp
from astroquery.vizier import Vizier
import astropy.coordinates as coord

from astropy.coordinates import SkyCoord  # High-level coordinates
from astropy.coordinates import ICRS, Galactic, FK4, FK5  # Low-level frames
from astropy.coordinates import Angle, Latitude, Longitude  # Angles
import astropy.units as u

from astropy.time import Time
import math

In [2]:
pd.options.display.max_rows=100

In [3]:
files = os.listdir('source')
files

['nearby_star_pm_anomalies20pc.dat',
 'nearby_star_pm_anomalies_plx33.dat',
 'nearby_star_pm_anomalies.dat',
 'nearby_star_pm_anomalies20pc (2).dat']

In [4]:
i = 1
infile = os.path.join('source', files[i])
print(infile)
df = pd.read_table(infile, sep='|')
df

source/nearby_star_pm_anomalies_plx33.dat

,source_id,ra,dec,phot_g_mean_mag,parallax,pmra,pmdec,delta_mu,delta_mu_un,pm_error,F,F_un,Unnamed: 12
0,4381249619862185600,253.312981,0.003492,15.813,33.1,-241.814,-143.115,25.0,19.5,9.8,2.5,2.0,NaN
1,1107588541411617536,94.030605,71.254607,14.210,33.1,254.030,-112.394,1.9,6.0,6.8,0.3,0.9,NaN
2,2256410856215182464,278.824590,64.355419,17.377,33.1,-134.032,113.891,13.3,23.9,19.7,0.7,1.2,NaN
3,3241886536733197312,76.698636,7.699864,14.556,33.1,-170.252,-205.015,4.6,5.2,6.2,0.7,0.8,NaN
4,1129856263213078912,170.663193,78.697791,15.540,33.1,-357.002,154.627,4.2,6.2,7.9,0.5,0.8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,5761985432616501376,133.398368,-3.493164,15.889,115.5,-516.605,-199.652,15.8,16.4,5.9,2.7,2.8,NaN
801,1165479168642900992,232.625560,9.434551,13.070,116.0,-178.853,183.898,4.3,8.8,7.5,0.6,1.2,NaN
802,3320184202856435840,89.104098,5.359345,13.967,123.2,-444.685,-925.140,9.2,10.0,6.5,1.4,1.5,NaN
803,2640434056928150400,353.797069,-2.392799,12.624,139.3,781.419,-841.516,19.5,18.9,8.8,2.2,2.1,NaN
804,685103912857072640,135.095643,21.832063,13.413,157.3,-514.942,-592.253,8.9,14.9,12.5,0.7,1.2,NaN

In [5]:
df.columns

Index(['                source_id', '          ra', '         dec',
       'phot_g_mean_mag', 'parallax', '     pmra', '    pmdec', 'delta_mu',
       'delta_mu_un', 'pm_error', '      F', '   F_un', 'Unnamed: 12'],
      dtype='object')

In [6]:
columnpairs = {c: c.strip() for c in df.columns}
df = df.rename(columns=columnpairs)
df.columns

Index(['source_id', 'ra', 'dec', 'phot_g_mean_mag', 'parallax', 'pmra',
       'pmdec', 'delta_mu', 'delta_mu_un', 'pm_error', 'F', 'F_un',
       'Unnamed: 12'],
      dtype='object')

In [7]:
df_or = df.loc[(df.F > 3) | (df.F_un > 3)]
print(len(df_or))
df_or

23

,source_id,ra,dec,phot_g_mean_mag,parallax,pmra,pmdec,delta_mu,delta_mu_un,pm_error,F,F_un,Unnamed: 12
128,2591201534008672256,18.001042,15.036510,15.604,35.1,166.116,-316.993,18.2,14.3,5.5,3.3,2.6,NaN
135,1341396287443528192,257.358899,39.157416,12.647,35.1,102.046,-665.381,18.7,25.6,5.8,3.2,4.4,NaN
137,4241358824189862784,296.058190,1.796250,15.506,35.1,-173.095,-433.729,46.5,49.0,7.2,6.5,6.8,NaN
143,658095646671391360,130.826211,15.913721,16.975,35.3,174.574,-151.633,41.7,43.6,7.9,5.3,5.5,NaN
163,658095646671391232,130.826185,15.913209,17.532,35.6,178.857,-149.782,40.1,41.8,7.9,5.1,5.3,NaN
199,2550544720750455040,8.930414,2.553021,14.419,36.1,170.383,-167.845,21.9,26.6,8.2,2.7,3.2,NaN
223,4033926506668450816,180.825031,38.877695,17.075,36.5,276.380,-486.875,26.8,30.8,5.5,4.9,5.6,NaN
363,1583484215025634688,187.286594,62.660186,16.678,39.8,-291.373,-266.919,14.3,22.0,6.8,2.1,3.2,NaN
385,215350076836032384,83.472965,50.904015,16.649,40.3,-154.269,-175.840,23.3,29.2,5.8,4.0,5.0,NaN
407,3974526181252628480,176.969368,17.710438,13.637,40.9,140.237,-149.023,28.0,25.5,8.6,3.3,3.0,NaN
427,4189472728736232704,299.464796,-10.886060,12.836,41.5,-390.525,-287.669,42.8,12.0,6.6,6.4,1.8,NaN
454,302525062400087936,27.288398,29.934868,18.258,42.4,172.759,-436.604,25.5,21.2,6.7,3.8,3.2,NaN
569,1104317391237838464,96.177950,66.439663,18.434,47.6,354.210,-519.494,24.8,27.4,6.9,3.6,4.0,NaN
629,565169459376414592,3.435789,80.664516,14.422,52.0,250.135,193.826,30.2,34.5,7.9,3.8,4.4,NaN
656,495091536024630656,61.487602,71.275534,14.639,54.6,166.660,-378.685,20.1,15.3,6.4,3.1,2.4,NaN
664,1228555023991501184,215.933913,14.445206,14.996,55.0,358.369,-544.221,36.0,41.0,9.8,3.7,4.2,NaN
694,1590096093840214272,221.506111,46.555032,13.231,58.6,496.880,-415.588,16.9,22.9,6.6,2.6,3.5,NaN
701,3181367767472670080,73.014966,-10.973691,14.141,59.1,-391.376,-218.224,35.6,41.0,7.1,5.0,5.8,NaN
707,523359498947960704,15.624864,63.543427,14.037,60.2,125.764,298.934,29.2,28.6,6.8,4.3,4.2,NaN
731,4594186745414679680,263.804744,26.578453,15.870,64.3,141.579,-289.130,31.7,36.6,6.3,5.0,5.8,NaN
770,1461125613285603840,197.393995,28.984195,12.576,77.9,-338.560,-203.980,25.6,18.7,6.9,3.7,2.7,NaN
777,4540481374832743040,259.432114,11.668138,13.209,80.8,-343.495,-450.857,42.8,44.4,7.4,5.8,6.0,NaN
782,4235280071072332672,299.119830,-1.045547,13.591,86.5,-437.759,-706.215,16.5,19.8,5.8,2.9,3.4,NaN

In [ ]:
df_F = df.loc[df.F > 3]
print(len(df_F))
df_F

In [ ]:
df_and = df.loc[(df.F > 2) & (df.F_un > 2)]
print(len(df_and))
df_and

In [ ]:
df.hist(column='F')

In [ ]:
df.corr()

In [ ]:
df_F.to_csv('F>3.dat', index=False, sep='|')

In [ ]:
pd.read_table('F>3.dat', sep='|')

In [ ]:
df_F15 = df_F[df_F.phot_g_mean_mag<15]

In [ ]:
bta_columns = 'Name                     | RA(J2000)    Dec(J2000)   | Filter|  Mag. |  Moon  | Total time (sec)'.split('|')
bta_columns

In [ ]:
Coords = []
Filter = []
Mag = []
Moon = []
Time = []

for index, row in df_F15.iterrows():
    c = SkyCoord(ra=row.ra * u.deg, dec=row.dec * u.deg)
    cs = c.to_string('hmsdms', sep=' ', precision=3)#.replace(' ', '|')
    print(cs)
    Coords.append(' '+cs)
    Filter.append('800/100')
    Mag.append(' '+str(row.phot_g_mean_mag)+' ')
    Moon.append('   any  ')
    Time.append('   100')

In [ ]:
#Coords, Filter, Mag, Moon, Time

In [ ]:
df_bta = pd.DataFrame(list(zip(list(df_F15.source_id), Coords, Filter, Mag, Moon, Time)),
               columns =bta_columns)
df_bta

In [ ]:
df_bta.to_csv('BTA_F>3.dat', index=False, sep='|')

In [ ]:
for index, row in df_F15.iterrows():
    print(str(row.ra)+', '+str(row.dec))

In [ ]:
df_F15[['ra', 'dec', 'source_id']]

In [ ]:
df_F15.to_csv('F>3_m<15.dat', index=False)#, sep='|')